[package]
name = "halfremembered-protocol"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde = { workspace = true }
bincode = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
bytes = { workspace = true }
log = { workspace = true }
